# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image & deploy
  jobs:
  - job: Build
    displayName: Build & deploy
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@0
      displayName: Build an image
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Azure demo'
        azureContainerRegistry: '{"loginServer":"jawahar.azurecr.io", "id" : "/subscriptions/4200e198-70f0-47e1-bbed-6b7fa83c3522/resourceGroups/NetworkWatcherRG/providers/Microsoft.ContainerRegistry/registries/jawahar"}'
        action: 'Build an image'
        dockerFile: '**/Dockerfile'
        imageName: '$(Build.Repository.Name):$(Build.BuildId)'
    - task: Docker@0
      displayName: push an image
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Azure demo'
        azureContainerRegistry: '{"loginServer":"jawahar.azurecr.io", "id" : "/subscriptions/4200e198-70f0-47e1-bbed-6b7fa83c3522/resourceGroups/NetworkWatcherRG/providers/Microsoft.ContainerRegistry/registries/jawahar1"}'
        action: 'push an image'
        imageName: '$(Build.Repository.Name):$(Build.BuildId)'
    - task: AzureWebAppContainer@1
      displayName: 'deploy: jawahar-container-dev'
      inputs:
        azureSubscription: 'Azure demo'
        appName: 'jawahar-container-dev'
    - task: AzureWebAppContainer@1
      displayName: 'deploy: jawahar-container-qa' 
      inputs:
        azureSubscription: 'Azure demo'
        appName: 'jawahar-container-qa'
