# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main
- dev

resources:
- repo: self

variables: 
  imageName: 'jawahar.azurecr.io/image-$(Build.Repository.Name):$(Build.SourceBranchName)-$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image & Deploy
  jobs: 
  - job: Build
    displayName: Build & deploy
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@0
      displayName: Build an Image
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Azure demo'
        azureContainerRegistry: '{"loginServer":"jawahar.azurecr.io", "id" : "/subscriptions/4200e198-70f0-47e1-bbed-6b7fa83c3522/resourceGroups/NetworkWatcherRG/providers/Microsoft.ContainerRegistry/registries/jawahar"}'
        action: 'Build an image'
        dockerFile: 'Dockerfile'
        imageName: '$(imageName)'
    - task: Docker@0
      displayName: push an image
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Azure demo'
        azureContainerRegistry: '{"loginServer":"jawahar.azurecr.io", "id" : "/subscriptions/4200e198-70f0-47e1-bbed-6b7fa83c3522/resourceGroups/NetworkWatcherRG/providers/Microsoft.ContainerRegistry/registries/jawahar"}'
        action: 'push an image'
        imageName: '$(imageName)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'Dockerfile'
        ArtifactName: 'drop'
        publishLocation: 'Container'